### ISSUE TITLE
non ID/PW connect then wxWidgets Debug alert happen

### ISSUE THREAD

**Issue by dhpark21** [Amebis/GEANTLink#21]
![error](https://cloud.githubusercontent.com/assets/12795655/18822571/555863dc-83ec-11e6-84b2-3ffe0a9610f1.PNG)

non ID/PW connect then wxWidgets Debug alert happen

**Comment by rozmansi** [comment]
Thank you for reporting this.
- This is a _Debug_ Alert - occurs only in Debug builds. In Release builds it does not appear.
- This is an extra sanity check in `wxItemContainer::GetClientObject()` (wxWidgets) before returning NULL, which is one of the expected scenarios in my code later on. Therefore, totally harmless.
- This occurs only when you have no user certificates installed and "&lt;empty&gt;" is the only choice in certificate selection control. The "&lt;empty&gt;" has no client object data itself and `wxChoice` remains configured to `wxClientData_None` instead of `wxClientData_Object` - which would be after the first certificate is added to the list.
