### ISSUE TITLE
No ID & PW No "OK" Butten Active

### ISSUE THREAD

**Issue by dhpark21** [Amebis/GEANTLink#22]
![pap](https://cloud.githubusercontent.com/assets/12795655/18859954/c18350e0-84b3-11e6-9dcf-f0f2e80d7863.PNG)
![eap](https://cloud.githubusercontent.com/assets/12795655/18859960/c4fefde6-84b3-11e6-8fc7-953daa911744.PNG)

I Think
User Did not type ID,PW Then OK butten did not Active
Check it

Thanks

**Comment by rozmansi** [comment]
Good you noticed that. However, that is by design:

> No credentials are credentials too.

Imagine credentials as a letter. You can put your message in the envelope and send it as a letter. You can put nothing in the envelope and send it as a letter too. Both are a letter. It is up to receiver, how he will treat each.

Example: TLS can have no client certificate and that is perfectly fine (in EAP-TTLS scenario). That only indicates server will skip client identity check.

A lot of GUI panels and code is shared between certificate and password based credentials in GÉANTLink. Therefore, same logic applies to all. Well, actually if the how-to-treat-empty-credentials logic would to be changed, it should probably adapt according to level of credentials (outer, inner), not their type.

Furthermore, PAP and MSCHAPv2 have no issues with sending empty credentials (blank username & password) too. How the server side will respond to that, GÉANTLink leaves it up to the server. Just remember to set outer identity manually then, as it serves as the routing hint to find authenticating server in the first place.

Therefore, GÉANTLink deliberately does not want to prejudice that empty credentials are not permitted by server. This decision is left for the authenticating server to decide.

When the server is unhappy with that, user will get:
![capture](https://cloud.githubusercontent.com/assets/6889694/18870270/23dad3e8-84b0-11e6-867c-048f91d5dc5b.PNG)
