### ISSUE TITLE
Windows GPO settings

### ISSUE THREAD

**Issue by akiparuk** [Amebis/GEANTLink#24]
Can you provide info how to or add feature to make profile  with settings to deploy it via GPO for windows 10?
For example. I want to transfer your app via GPO and create WLAN access point with ttls+pap. assign CA certificate to that WLAN but let user to choose a password.
In latest Versions of windows I can change settings for connection only when it is connected.
if it is not working or configured improperly there is no way change settings because  that dialog box was removed from control panel.
The only way to change settings is to remove access point and create it once again.
so it would be nice if you add availability to change that settings in your app.
Thanx

**Comment by rozmansi** [comment]
Yes, this is a frustration. Talk to Microsoft. GEANTLink provides a helper utility to allow editing WiFi profiles on clients. Please download and run `WLANManager-Win32.exe` or `WLANManager-x64.exe` from the command line:

```
WLANManager-Win32 profile <your profile name>
```

Use `Win32`or `x64`depending on Windows installed.

I deploy EAP WiFi profiles like this:
1. Deploy GEANTLink MSI to workstations/laptops.
2. Install GEANTLink on the server you are configuring GPO with. Otherwise, it will not show on the list of EAP methods.
3. Edit existing or create new GPO policy and go to _Computer Configuration_ >> _Policies_ >> _Windows Settings_ >> _Security Settings_ >> _Wireless Network (IEEE 802.11) Policies_ >> _Create a new Windows Vista or later policy..._ >> _Add..._ >> _Infrastructure_. Configure your WiFi here and under Security tab select _WPA2-Enterprise_ and _GEANTLink: EAP-TTLS_ as authentication method:
![screen shot 2017-10-16 at 20 14 29](https://user-images.githubusercontent.com/6889694/31627800-d327821a-b2ae-11e7-908a-ac313b3d99fb.png)
   And configure all other settings for your network of course.
