### ISSUE TITLE
No credential window appears with 1.2g

### ISSUE THREAD

**Issue by ikreb7** [Amebis/GEANTLink#28]
Hello Simon,

thank you very much for the new release. Sadly, now we have the problem, that sometimes no window for the credentials appears. Do you have any idea for this problem?

I will try to collect more information.

**Comment by rozmansi** [comment]
The credential window should appear when a user clicks on "Connect" button in the network list that is displayed when you click the network icon in the system tray.

**Comment by ikreb7** [comment]
Yes, but this happens not every time after a fresh installing.

**Comment by tgrisel** [comment]
Same problem here. Mostly, the window appears shortly and disappears. Network-manager says "No connection to this network possible."

**Comment by rozmansi** [comment]
I tried to reproduce this issue (or issues).

The following is normal and expected behaviour on Windows 10:

1. Credential prompt only pops up when you _click_ to connect to the network. When the network is set to connect automatically, but the profile has no saved credentials to do so, one must still click to connect to the network manually. Then the credential prompt should appear.

2. When the credential prompt is activated, if you click the Network icon on the system tray, the credential prompt will be cancelled. Windows believes you changed your mind and wish to connect to something else. See the screencast: https://1drv.ms/v/s!AsRKV9itoeUTi0ly9EO4_KlE6m_O

3. However, when the credential prompt is activated, you may click around and switch to another application (e.g. to copy your password from a password-keeping app). The credential prompt remains and allows you to complete connecting. See the screencast: https://1drv.ms/v/s!AsRKV9itoeUTi0p9sVvHPKdvY61w

4. However, the credential prompt expires after 30 seconds. This is very short for disabled people, or if you need to go copy your credentials from a password-keeping app.
